# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

trigger:
 branches:
   include:
     - releases/preview*

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Set current .NET version to $(dotnet_version)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnet_version)'

- task: DotNetCoreCLI@2
  displayName: 'Package Core project to nuget.'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/src/framework/**/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(nuget_version_major)'
    minorVersion: '$(nuget_version_minor)'
    patchVersion: '$(nuget_version_patch)'

- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'MiCake_NuGet_Key'
  
- script: dotnet nuget push --api-key MiCake_NuGet_Key --source https://api.nuget.org/v3/index.json  "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"